### ISSUE TITLE
objects as closed set

### ISSUE THREAD

**Issue by bebbi** [pieper/cvg#16]
is it ok to represent all bounded expressions as closed sets? (s/</<=/)
Main reason: while introducing "cut by plane", if cut a box at plane at origin, I should have a rectangle rather than empty set
Aside, with a improved/"binary" mc function, closed sets would seem to better represent measurements in finite resolution.

**Comment by pieper** [comment]
By the way whenever this comes up we should be left-closed and right-open (i.e. consider the binary representation of the coordinate where the most significant bit divides the space in half).

https://en.wikipedia.org/wiki/Interval_(mathematics) :
"The interval [0,1) = {x | 0 ≤ x < 1}, for example, is left-closed and right-open."
